### ISSUE TITLE
User Home Page

### ISSUE THREAD

**Issue by janeligio** [shooots/shooots#1]
![img_0453](https://user-images.githubusercontent.com/28047474/32642236-ecf7f078-c576-11e7-8711-d651e46a07e4.JPG)

![image](https://user-images.githubusercontent.com/28047474/32710708-75ebf7ee-c7de-11e7-90a4-ca9557d8fef2.png)

**Comment by sharieannem** [comment]
Change bullet points to semantic ui cards

**Comment by janeligio** [comment]
change color scheme
