### ISSUE TITLE
Filter Page (find a ride) Functionality

### ISSUE THREAD

**Issue by jasonhuang23** [shooots/shooots#15]
Remove Interests filter
Add time slot filter - make it simple ~morning, noon, and evening

**Comment by janeligio** [comment]
This is how it looks like right now 
![updatedfilterpage](https://user-images.githubusercontent.com/22269991/33547499-56000988-d888-11e7-89dc-5fac021eaf2e.JPG)

**Comment by janeligio** [comment]
Filtered by morning drivers 
![filter_morning](https://user-images.githubusercontent.com/22269991/33550972-eb2d52c6-d893-11e7-91d9-db9bfb30fd38.JPG)

**Comment by janeligio** [comment]
Filtered by afternoon drivers
![filter_noon](https://user-images.githubusercontent.com/22269991/33551002-fe2c7a46-d893-11e7-9630-14e21f6d5a50.JPG)

**Comment by janeligio** [comment]
Filtered by evening drivers (there are no drivers in that slot)
![filter_evening](https://user-images.githubusercontent.com/22269991/33551017-0acb4a66-d894-11e7-9469-4654cfe896b7.JPG)
