### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by sharieannem** [shooots/shooots#2]
![screen shot 2017-11-09 at 5 43 23 pm](https://user-images.githubusercontent.com/28047474/32642025-a9c5c844-c575-11e7-98f2-a5fe795d2f1f.png)
![screen shot 2017-11-09 at 5 43 41 pm](https://user-images.githubusercontent.com/28047474/32642029-af0066ca-c575-11e7-8ac4-291664324001.png)

**Comment by sharieannem** [comment]
Update layout of Landing Page

**Comment by jasonhuang23** [comment]
![landing-page 1](https://user-images.githubusercontent.com/28047474/33578732-a2fa41b4-d8eb-11e7-9fd5-91185d4afe9a.png)
![landing-page 2](https://user-images.githubusercontent.com/28047474/33578733-a32d4afa-d8eb-11e7-8e81-91abdf398aa0.png)
![landing-page 3](https://user-images.githubusercontent.com/28047474/33578734-a3517ec0-d8eb-11e7-903f-c6f21f3111c9.png)
![landing-page 4](https://user-images.githubusercontent.com/28047474/33578735-a3722d8c-d8eb-11e7-98bd-e0a1dbba54fd.png)
![landing-page 5](https://user-images.githubusercontent.com/28047474/33578737-a391d466-d8eb-11e7-9ef4-82c399469cf4.png)
