### ISSUE TITLE
Rating Page

### ISSUE THREAD

**Issue by jasonhuang23** [shooots/shooots#5]
paper and pencil mockup of ratings page
![ratingspage](https://user-images.githubusercontent.com/22269991/32642120-23b41962-c576-11e7-9664-701f559da323.jpg)

**Comment by janeligio** [comment]
![ratings-page-mockuip](https://user-images.githubusercontent.com/22269991/33149791-20b08620-cf75-11e7-8bca-3dff9379afb7.JPG)

ratings page html mockup

**Comment by janeligio** [comment]
app/client/main.js : imported ratings directory
Created new directory-profile-ratings.html file that mirrors bowfolios' directory-profile.html file, and it is used in the ratings page template to display drivers and their ratings

Created whole new ratings directory and wired it to router so it shows up in menubar. Made Ratings_Page_Directory template that is used in Ratings_Page similar to how filter page displays users.

Note: Ratings aren't actually functional at the moment and it simply an icon.
