### ISSUE TITLE
Filter Page

### ISSUE THREAD

**Issue by jasonhuang23** [shooots/shooots#6]
paper and pencil mockup of filter page
![filterpage](https://user-images.githubusercontent.com/22269991/32642063-e7b2731e-c575-11e7-8322-a44a6104c56c.jpg)

**Comment by janeligio** [comment]
Added city, and zipcode. I'm going to modify the profiles to have a schedule button. Have to decide on what information users should have so we can have one singular Commuter (or whatever we're going to call the collection) collection that we can play around with in our mockups. 
![filter-page-mockup](https://user-images.githubusercontent.com/22269991/32694802-e949c370-c6ed-11e7-9cf3-44699be2c674.JPG)

**Comment by janeligio** [comment]
Maybe change "filter" to find a ride
